version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: metis_connect
      POSTGRES_USER: metis
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metis"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://metis:password@postgres:5432/metis_connect
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  rasa:
    image: rasa/rasa:3.6.0
    ports:
      - "5005:5005"
    volumes:
      - ./backend/rasa:/app
    command: run --enable-api --cors "*" --debug

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start

volumes:
  postgres_data: